name: FIAB
services:
  forecast-in-a-box:
    restart: unless-stopped
    container_name: forecast-in-a-box
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/app/data_dir
      - ~/fiab:/root/.fiab
    ports:
      - "8000:8000"
    environment:
      fiab__API__DATA_PATH: "/app/data_dir/"
      fiab__AUTH__PUBLIC_URL: ???

      ECMWF_API_URL: "https://api.ecmwf.int/v1"
      ECMWF_API_KEY: ${ECMWF_API_KEY}
      ECMWF_API_EMAIL: ${ECMWF_API_EMAIL}

      FIAB_INSTALL_TYPE: all

      EARTHKIT_DATA_USER_CACHE_DIRECTORY: /app/data_dir/earthkit_cache
      EARTHKIT_DATA_CACHE_POLICY: "user"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  data:
