name: FIAB

services:
  frontend:
    container_name: fiab-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: eccr.ecmwf.int/forecast-in-a-box/fiab-frontend:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      API_URL: "http://localhost:8000"
    # networks:
    #   - fiab-network
    #   - host
    
  backend:
    container_name: fiab-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: eccr.ecmwf.int/forecast-in-a-box/fiab-backend:latest
    volumes:
      - data:/app/data_dir
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "8000:8000"
    environment:
      API_URL: "http://localhost:8000"
      DATA_PATH: "/app/data_dir"
      MODEL_REPOSITORY: "https://sites.ecmwf.int/repository/fiab"
      CASCADE_URL: "tcp://localhost:8067"
      MONGODB_URI: "mongodb://localhost:27017"
      MONGODB_DATABASE: "fiab"

      ECMWF_API_URL: "https://api.ecmwf.int/v1"
      ECMWF_API_KEY: ${ECMWF_API_KEY}
      ECMWF_API_EMAIL: ${ECMWF_API_EMAIL}

      FIAB_INSTALL_TYPE: all

    networks:
      - fiab-network

networks:
  fiab-network:
    driver: bridge
  host:
    external: true
    name: host

volumes:
  data: