name: FIAB
services:

  frontend:
    container_name: fiab-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: ghcr.io/ecmwf/forecast-in-a-box/frontend
    ports:
      - "3000:3000"
    networks:
      - fiab-network

  backend:
    container_name: fiab-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: ghcr.io/ecmwf/forecast-in-a-box/backend
    volumes:
      - data:/app/data_dir
      - ~/.fiab:/root/.fiab
    ports:
      - "8000:8000"
    environment:
      # fiab__FRONTEND_URL: "https://DOMAIN"
      fiab__API__API_URL: "http://backend:8000"
      fiab__API__DATA_PATH: "/app/data_dir"
      fiab__API__MODEL_REPOSITORY: "https://sites.ecmwf.int/repository/fiab"
      fiab__CASCADE__CASCADE_URL: "tcp://cascade:8067"

      ECMWF_API_URL: "https://api.ecmwf.int/v1"
      ECMWF_API_KEY: ${ECMWF_API_KEY}
      ECMWF_API_EMAIL: ${ECMWF_API_EMAIL}

      FIAB_INSTALL_TYPE: all
    networks:
      - fiab-network

  cascade:
    container_name: fiab-cascade
    build:
      context: ./cascade
      dockerfile: Dockerfile
    # image: ghcr.io/ecmwf/forecast-in-a-box/cascade
    entrypoint: "python -m cascade.gateway tcp://0.0.0.0:8067"
    networks:
      - fiab-network
    ports:
      - "48165:48165"
    shm_size: '5gb'
    volumes:
      - data:/app/data_dir
      - ~/.ecmwfapirc:/root/.ecmwfapirc:ro
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


networks:
  fiab-network:
    driver: bridge
  host:
    external: true
    name: host

volumes:
  data:
  # frontend-dist:
