name: FIAB

services:
  frontend:
    container_name: fiab-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          NEXT_PUBLIC_API_URL: "http://backend:8000" # Pass the variable during build
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
    networks:
      - fiab-network
    
  backend:
    container_name: fiab-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - fiab_data:/app/data_dir
      - './../anemoi-cascade:/app/anemoi-cascade'
    ports:
      - "8000:8000"
    environment:
      API_URL: "http://localhost:8000"
      DATA_PATH: "/app/data_dir"
      MODEL_REPOSITORY: "https://sites.ecmwf.int/repository/fiab/"
      CASCADE_URL: "tcp://localhost:8067"
      MONGODB_URI: "mongodb://localhost:27017"
      MONGODB_DATABASE: "fiab"
    networks:
      - fiab-network

networks:
  fiab-network:
    driver: bridge