val:
    uv run ty check src/
    just test

test:
    FIAB_IGNORE_CONFIG_SOURCES=1 uv run pytest -n4 tests/unit
    FIAB_IGNORE_CONFIG_SOURCES=1 uv run pytest tests/integration

dev:
    just -f ../justfile dev
