#!/usr/bin/env python3
#
# (C) Copyright 2026- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

"""Convert a frontend FableBuilderV1 JSON dump to a BlueprintTemplate Python source file.

Usage:
    python blueprint_to_template.py < job.json > template.py

The input is the frontend FableBuilderV1 format (as exported by the UI or stored per-job),
where ``blocks`` is a dict keyed by block instance id, each entry carrying a ``factory_id``
with ``plugin`` and ``factory`` sub-fields, plus ``configuration_values`` and ``input_ids``.

The output is a standalone Python file that defines a ``template`` variable of type
``BlueprintTemplate`` ready to be imported and registered in a plugin.

Review all ``# TODO`` comments in the output before committing.
"""

# TODO dont use the blockInstanceId in the input -- instead, use "human readable", derived from the block name. For example, "block_1784116163887_4my2dcp" block instance id of a block factory BlockFactoryId("operationalForecastSource") should be replaced by BlockInstanceId("operationalForecastSource"). However, block instance ids need to be unique, so you would need to scan the whole json for unicity of the factory ids, and enumerate where there are conflicts. Note you need to do the remapping *also* in the input ids, consistently!
# TODO add in means to choose whether a given local glyph's value should be hardcoded or should go to example values
# TODO add in means to query backend endpoint directly with a given blueprint id / run id, instead of requiring the user to download the json manually by hand. Alternatively, add this functionality to the rust cli, so that we just pipe them together
# TODO add in regime that would ask the user for a filename + plugin, and place it to the right location and handle the registration in the outer plugin class as well
# TODO make it part of fiab-core or backend functionality, include an endpoint that would take blueprint id, local-or-example, and path to save it at (or plugin name + fname inside templates/ directory), and invoke it from the frontend

import json
import sys
from typing import Any


def _q(s: str) -> str:
    """Return a Python string literal for s."""
    return repr(s)


def _indent(lines: list[str], n: int) -> list[str]:
    prefix = "    " * n
    return [prefix + line if line.strip() else line for line in lines]


def _render_config_values(config_values: dict[str, str], depth: int) -> list[str]:
    if not config_values:
        return ["configuration_values={},"]
    lines = ["configuration_values={"]
    for k, v in config_values.items():
        lines.append(f"    ConfigurationOptionId({_q(k)}): {_q(v)},")
    lines.append("},")
    return _indent(lines, 0) if depth == 0 else lines


def _render_input_ids(input_ids: dict[str, str], depth: int) -> list[str]:
    if not input_ids:
        return ["input_ids={},"]
    lines = ["input_ids={"]
    for k, v in input_ids.items():
        lines.append(f"    {_q(k)}: BlockInstanceId({_q(v)}),")
    lines.append("},")
    return lines


def generate(data: dict[str, Any]) -> str:
    blocks: dict[str, Any] = data.get("blocks") or {}
    local_glyphs: dict[str, str] = data.get("local_glyphs") or {}
    environment: dict[str, Any] | None = data.get("environment")
    env_vars: dict[str, str] = (environment or {}).get("environment_variables") or {}

    needs_env = bool(env_vars)

    out: list[str] = []

    # -- license header --
    out += [
        "# (C) Copyright 2026- ECMWF.",
        "#",
        "# This software is licensed under the terms of the Apache Licence Version 2.0",
        "# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.",
        "#",
        "# In applying this licence, ECMWF does not waive the privileges and immunities",
        "# granted to it by virtue of its status as an intergovernmental organisation",
        "# nor does it submit to any jurisdiction.",
        "",
        "# Generated by fiab-core/scripts/blueprint_to_template.py.",
        "# Review all # TODO comments and fill in the blanks before use.",
        "",
    ]

    # -- imports --
    import_names = [
        "BlockInstance",
        "BlockInstanceId",
        "BlockFactoryId",
        "BlueprintTemplate",
        "BlueprintTemplateBlock",
        "BlueprintTemplateExampleInput",
        "ConfigurationOptionId",
    ]
    if needs_env:
        import_names.append("BlueprintTemplateEnvironment")
    import_names.sort()

    out.append("from fiab_core.fable import (")
    for name in import_names:
        out.append(f"    {name},")
    out.append(")")
    out += ["", ""]

    # -- template variable --
    out.append("template = BlueprintTemplate(")
    out.append('    display_name="",  # TODO put content here')
    out.append('    display_description="",  # TODO put content here')

    # -- blocks --
    out.append("    blocks={")
    for block_id, block_data in blocks.items():
        factory_id: str = block_data["factory_id"]["factory"]
        config_values: dict[str, str] = block_data.get("configuration_values") or {}
        input_ids: dict[str, str] = block_data.get("input_ids") or {}

        out.append(f"        BlockInstanceId({_q(block_id)}): BlueprintTemplateBlock(")
        out.append(f"            factory_id=BlockFactoryId({_q(factory_id)}),")
        out.append("            instance=BlockInstance(")

        cfg_lines = _render_config_values(config_values, depth=0)
        out += _indent(cfg_lines, 4)

        inp_lines = _render_input_ids(input_ids, depth=0)
        out += _indent(inp_lines, 4)

        out.append("            ),")
        out.append("        ),")
    out.append("    },")

    # -- environment --
    if needs_env:
        out.append("    environment=BlueprintTemplateEnvironment(")
        out.append("        environment_variables={")
        for k, v in env_vars.items():
            out.append(f"            {_q(k)}: {_q(v)},")
        out.append("        },")
        out.append("    ),")
    else:
        out.append("    environment=None,")

    # -- local_glyphs: empty; values go to example_glyphs --
    out.append("    local_glyphs={},")

    # -- example_glyphs: populated from local_glyphs in the source JSON --
    if local_glyphs:
        out.append("    example_glyphs={")
        for glyph_key, glyph_value in local_glyphs.items():
            out.append(f"        {_q(glyph_key)}: BlueprintTemplateExampleInput(")
            out.append(f"            example_value={_q(glyph_value)},")
            out.append("            display_name=None,  # TODO put content here")
            out.append("            display_description=None,  # TODO put content here")
            out.append("            type_hint=None,  # TODO put content here")
            out.append("        ),")
        out.append("    },")
    else:
        out.append("    example_glyphs={},")

    out.append(")")
    out.append("")

    return "\n".join(out)


def main() -> None:
    data = json.load(sys.stdin)
    sys.stdout.write(generate(data))


if __name__ == "__main__":
    main()
