# (C) Copyright 2026- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

# Generated by fiab-core/scripts/blueprint_to_template.py.
# Review all # TODO comments and fill in the blanks before use.

from fiab_core.fable import (
    BlockFactoryId,
    BlockInstance,
    BlockInstanceId,
    BlueprintTemplate,
    BlueprintTemplateBlock,
    BlueprintTemplateExampleInput,
    ConfigurationOptionId,
)

template = BlueprintTemplate(
    display_name="",  # TODO put content here
    display_description="",  # TODO put content here
    blocks={
        BlockInstanceId("block_1784116163887_4my2dcp"): BlueprintTemplateBlock(
            factory_id=BlockFactoryId("operationalForecastSource"),
            instance=BlockInstance(
                configuration_values={
                    ConfigurationOptionId("source"): "ecmwf-open-data",
                    ConfigurationOptionId("forecast"): "ifs-ens",
                    ConfigurationOptionId("base_time"): "${submitDatetime |floor_day}",
                },
                input_ids={},
            ),
        ),
        BlockInstanceId("block_1784116184409_sdaoh52"): BlueprintTemplateBlock(
            factory_id=BlockFactoryId("select"),
            instance=BlockInstance(
                configuration_values={
                    ConfigurationOptionId("dimension"): "param",
                    ConfigurationOptionId("values"): "2t",
                },
                input_ids={
                    "dataset": BlockInstanceId("block_1784116163887_4my2dcp"),
                },
            ),
        ),
        BlockInstanceId("block_1784116202433_qaqj75m"): BlueprintTemplateBlock(
            factory_id=BlockFactoryId("gribSink"),
            instance=BlockInstance(
                configuration_values={
                    ConfigurationOptionId("path"): "${outputRoot}/${runId}.${attemptCount}",
                },
                input_ids={
                    "dataset": BlockInstanceId("block_1784116184409_sdaoh52"),
                },
            ),
        ),
    },
    environment=None,
    local_glyphs={},
    example_glyphs={
        "outputRoot": BlueprintTemplateExampleInput(
            example_value="/tmp/outputRoot",
            display_name=None,  # TODO put content here
            display_description=None,  # TODO put content here
            type_hint=None,  # TODO put content here
        ),
    },
)
