# dockerfile with a released fiab
# - on top of Dockerfile-base
# - the specified release, pulled in at the build time
# - no config override, meaning all defaults

FROM fiab-base:latest 

# NOTE the launcher is taken from main and replaces itself with the one of the release during the warmup
ARG RELEASE_TAG="v0.0.0"
RUN : \
    && curl -fLsS https://raw.githubusercontent.com/ecmwf/forecast-in-a-box/main/scripts/fiab.sh > /home/fiab/fiab.sh \
    && chmod u+x /home/fiab/fiab.sh \
    && /home/fiab/fiab.sh warmup "$RELEASE_TAG" \
    && : ;

ENTRYPOINT ["/home/fiab/fiab.sh"]
