# dockerfile base for a fiab runtime
# - slim debian as a base
# - packages (bash+curl) for basic executability + getting remote data at runtime
# - packages (libgfortran & friends) for being able to load ecmwf atlas lib
# - packages (gdal) for that fiona unbuildable wheel required by ek plots < 1.0
# - no fiab itself, thats in either Dockerfile-dev or Dockerfile-release

FROM debian:stable-slim

RUN : \
    && apt-get update \
    && apt-get install -y bash curl ca-certificates \
    && apt-get install -y libgfortran5 libquadmath0 libgomp1 \
    && apt-get install -y gdal-bin libgdal-dev g++ \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --system --user-group --create-home --shell /bin/false fiab \
    && : ;

USER fiab
