# TODO add Dockerfile-gpu and Dockerfile-dist-*, and differentiate commands below with an arg (plain/gpu/dist)

build:
    cp ../../scripts/fiab.sh . # NOTE we could have context the repo root -- but too bulky and not needed
    # TODO tag with the release version?
    docker build -t fiab-base -f Dockerfile-plain .

run:
    docker run --rm -it -p 8000:8000 fiab-base

# TODO add command for publish
# TODO add command for integration test
