# (C) Copyright 2024- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

"""Service layer for the job execution domain.

Owns:
- compile-and-submit flow (execute),
- restart flow,
- status polling with cascade,
- linked-blueprint lookup,
- output availability / content lookups,
- logs packaging.

No HTTP exceptions are raised here; callers are responsible for mapping domain
exceptions (``RunNotFound``, ``RunAccessDenied``) to HTTP responses.

Authorization is enforced via ``domain.run.db`` which filters / rejects
based on the supplied ``AuthContext``.
"""

import asyncio
import logging
from typing import cast

import cascade.gateway.api as api
import cascade.gateway.client as client
from cascade.low.func import Either
from pydantic import BaseModel

import forecastbox.domain.blueprint.db as blueprint_db
import forecastbox.domain.run.db as run_db
from forecastbox.domain.run.background import execute_background
from forecastbox.domain.run.db import CompilerRuntimeContext
from forecastbox.domain.run.exceptions import RunNotFound
from forecastbox.schemata.jobs import Blueprint, Run
from forecastbox.utility.auth import AuthContext
from forecastbox.utility.config import config

logger = logging.getLogger(__name__)


class RunDetail(BaseModel):
    """Detail of a single job execution attempt."""

    run_id: str
    attempt_count: int
    status: str
    created_at: str
    updated_at: str
    blueprint_id: str
    blueprint_version: int
    error: str | None = None
    progress: str | None = None
    cascade_job_id: str | None = None


class ExecuteResult(BaseModel):
    """Result of a job execution submission."""

    run_id: str
    """Logical execution id (Run.id)."""
    attempt_count: int
    """Attempt number; always 1 on a fresh execution."""


async def get_blueprint_for_execution(blueprint_id: str, blueprint_version: int | None) -> Blueprint | None:
    """Retrieve a Blueprint from the jobs store by id and optional version."""
    return await blueprint_db.get_blueprint(blueprint_id, blueprint_version)


async def execute(
    blueprint: Blueprint,
    auth_context: AuthContext,
    run_id: str | None = None,
    experiment_id: str | None = None,
    experiment_version: int | None = None,
    compiler_runtime_context: CompilerRuntimeContext = CompilerRuntimeContext(),
    experiment_context: str | None = None,
) -> Either[ExecuteResult, str]:  # type: ignore[invalid-argument]
    """Always creates a Run linked to the given Blueprint.

    Inserts a Run row immediately and returns an ExecuteResult, then fires off
    compilation and cascade submission in a thread-pool executor so the async loop
    is not blocked.  When ``run_id`` is supplied the new attempt is appended under
    that existing id (restart semantics); otherwise a fresh id is generated by the
    database layer.  Experiment metadata is stored on the row when provided and
    preserved on restart.
    """
    if not blueprint.blocks:
        return Either.error(f"Blueprint {blueprint.blueprint_id!r} has no compilable blocks")

    blueprint_id = str(blueprint.blueprint_id)  # ty:ignore[invalid-argument-type]
    blueprint_version = cast(int, blueprint.version)

    new_run_id, attempt_count, created_at = await run_db.upsert_run(
        run_id=run_id,
        blueprint_id=blueprint_id,
        blueprint_version=blueprint_version,
        created_by=auth_context.user_id,
        status="submitted",
        experiment_id=experiment_id,
        experiment_version=experiment_version,
        experiment_context=experiment_context,
    )

    loop = asyncio.get_running_loop()
    loop.run_in_executor(
        None,
        execute_background,
        new_run_id,
        attempt_count,
        created_at,
        blueprint,
        compiler_runtime_context,
        loop,
        auth_context,
    )

    return Either.ok(ExecuteResult(run_id=new_run_id, attempt_count=attempt_count))


async def restart_run(run_id: str, auth_context: AuthContext) -> Either[ExecuteResult, str]:  # type: ignore[invalid-argument]
    """Create a new attempt under an existing run_id, re-running its linked Blueprint.

    Raises ``RunNotFound`` if the execution does not exist.
    Raises ``RunAccessDenied`` if the actor does not own the execution.
    """
    existing = await run_db.get_run(run_id, auth_context=auth_context)
    # get_run raises RunNotFound / RunAccessDenied on failure.

    blueprint_id = str(existing.blueprint_id)  # ty:ignore[invalid-argument-type]
    blueprint_version = cast(int, existing.blueprint_version)
    blueprint = await blueprint_db.get_blueprint(blueprint_id, blueprint_version)
    if blueprint is None:
        return Either.error(f"Blueprint {blueprint_id!r} v{blueprint_version} not found")

    raw_context = cast(dict, existing.compiler_runtime_context)
    context = CompilerRuntimeContext.model_validate(raw_context)

    return await execute(
        blueprint,
        auth_context,
        run_id=run_id,
        experiment_id=cast(str | None, existing.experiment_id),
        experiment_version=cast(int | None, existing.experiment_version),
        compiler_runtime_context=context,
        experiment_context=cast(str | None, existing.experiment_context),
    )


async def poll_and_update(execution: Run) -> RunDetail:
    """Poll cascade for a Run's status, update db if changed, and return current detail."""
    run_id = str(execution.run_id)  # ty:ignore[invalid-argument-type]
    actual_attempt = cast(int, execution.attempt_count)
    cascade_job_id = cast(str | None, execution.cascade_job_id)
    status = cast(str, execution.status)

    def _build(status_override: str | None = None, error_override: str | None = None, progress_override: str | None = None) -> RunDetail:
        return RunDetail(
            run_id=str(execution.run_id),  # ty:ignore[invalid-argument-type]
            attempt_count=actual_attempt,
            status=status_override or status,
            created_at=str(execution.created_at),
            updated_at=str(execution.updated_at),
            blueprint_id=str(execution.blueprint_id),  # ty:ignore[invalid-argument-type]
            blueprint_version=cast(int, execution.blueprint_version),
            error=error_override if error_override is not None else cast(str | None, execution.error),
            progress=progress_override if progress_override is not None else cast(str | None, execution.progress),
            cascade_job_id=cascade_job_id,
        )

    if status in ("submitted", "preparing", "running") and cascade_job_id:
        try:
            response = client.request_response(api.JobProgressRequest(job_ids=[cascade_job_id]), f"{config.cascade.cascade_url}")
            response = cast(api.JobProgressResponse, response)
        except TimeoutError:
            return _build(status_override="unknown", error_override="failed to communicate with gateway")
        except Exception as e:
            return _build(status_override="unknown", error_override=f"internal cascade failure: {repr(e)}")

        if response.error:
            return _build(status_override="unknown", error_override=response.error)

        jobprogress = response.progresses.get(cascade_job_id)
        if jobprogress is None:
            await run_db.update_run_runtime(run_id, actual_attempt, status="failed", error="evicted from gateway")
            return _build(status_override="failed", error_override="evicted from gateway")
        elif jobprogress.failure:
            await run_db.update_run_runtime(run_id, actual_attempt, status="failed", error=jobprogress.failure)
            return _build(status_override="failed", error_override=jobprogress.failure)
        elif jobprogress.completed or jobprogress.pct == "100.00":
            await run_db.update_run_runtime(run_id, actual_attempt, status="completed", progress="100.00")
            return _build(status_override="completed", progress_override="100.00")
        else:
            await run_db.update_run_runtime(run_id, actual_attempt, status="running", progress=jobprogress.pct)
            return _build(status_override="running", progress_override=jobprogress.pct)

    return _build()
