name: bigtest

# DA BIG TEST
# launches the backend, downloads a model, executes full blown forecast job, ensures success
# not executed regularly, this is too much dakka

on:
  # Trigger the workflow manually
  workflow_dispatch: ~


jobs:
  macos:
    name: macos
    strategy:
      fail-fast: true
      matrix:
        arch_type: [ARM64]
        python_version: ["3.11"] # replace with 3.14 in ~26/01, once all wheels etc available
    runs-on: [self-hosted, macOS, "${{ matrix.arch_type }}"]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - working-directory: backend/tests/largeE2E
        run: |
          set -euo pipefail
          just install
          trap 'just stop' EXIT
          just start
          just run
