name: Build and Push Docker Images

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and push'
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - backend
          - frontend
          - cascade
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env variables
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
            export TAG=${{ github.event.inputs.tag }}
          else
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            export TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "IMAGE_NAME=${{ matrix.image }}" >> $GITHUB_ENV
          echo "REPO_IMAGE=ghcr.io/${{ github.repository }}/${{ matrix.image }}:$TAG" >> $GITHUB_ENV

      - name: Build image
        run: |
          echo "Building image: $REPO_IMAGE - with tag: ${TAG}"
          docker compose build --build-arg TAG=${TAG} $IMAGE_NAME
        env:
          TAG: ${{ env.TAG }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          REPO_IMAGE: ${{ env.REPO_IMAGE }}

      - name: Tag image
        run: |
          docker tag fiab-$IMAGE_NAME $REPO_IMAGE
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          REPO_IMAGE: ${{ env.REPO_IMAGE }}

      - name: Push image
        run: |
          echo "Pushing image: $REPO_IMAGE"
          docker push $REPO_IMAGE
        env:
          REPO_IMAGE: ${{ env.REPO_IMAGE }}