name: Build and Push Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - backend
          - frontend
          - cascade
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          IMAGE_NAME=$(echo "${{ matrix.image }}" | sed "s|\${TAG}|${TAG}|g")
          REPO_IMAGE=ghcr.io/${{ github.repository_owner }}/$(basename $IMAGE_NAME):${TAG}
          docker compose build --build-arg TAG=${TAG} $IMAGE_NAME
          docker tag $IMAGE_NAME $REPO_IMAGE
          docker push $REPO_IMAGE
        env:
          TAG: ${{ env.TAG }}