name: CD for fiab-core and fiab-plugin-test

# Releases fiab-core (and fiab-plugin-test, as that one is effectively used to
# test core-backend interactions and its changes are coupled to core changes).
#
# It pushes a new tag cX.Y.Z.0, either provided on input, or derived from
# the git repo as the highest existing tag + 0.0.1.
# It builds and then tests the two wheels in isolation, each versioned X.Y.Z,
# then pushes to PyPI.

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Explicit tag. Use cX.Y.Z, make sure its free on pypi
        type: string
        required: false
      testpypi:
        description: Whether to upload to testpypi instead of pypi.
        type: boolean
        required: false
        default: false


jobs:
  buildupload:
    name: "Build and upload"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: astral-sh/setup-uv@v7
      - uses: extractions/setup-just@v3
      - run: |
          echo "placeholder"

