name: CD for the application itself (backend & frontend)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Explicit tag, use to override the default patch-increment strategy
        type: string
        required: false
      testpypi:
        description: Whether to upload to testpypi instead of pypi.
        type: boolean
        required: false
        default: false

# TODO integrate with https://github.com/googleapis/release-please

jobs:
  # TODO add a prerequisite step `bigtest.yml` workflow, but make sure its reliable first
  deploy:
    name: "Build, upload and tag"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-node@v4
      - run: |
          # NOTE dont use action checkout, doesnt coop with auth
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          git clone -b $BRANCH --single-branch https://$GH_USER:$GH_TOKEN@github.com/ecmwf/forecast-in-a-box.git .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://$GH_USER:$GH_TOKEN@github.com/ecmwf/forecast-in-a-box.git
          git fetch --tags origin # NOTE dont use with: fetch-tags: true, the clone is still shallow

          source scripts/cicd/scripts.sh
          setupBash "${{ inputs.testpypi }}" 
          REPO_ROOT=$(pwd)

          # derive the tag
          TAG_PREF="v"
          TAG=$(tagFromInputOrLatest "${{ inputs.tag }}" $TAG_PREF)
          preparePythonWheelVersion $TAG
          TAG_FIABCORE=$(extractFiabCoreTag "$TAG")
          TAG_FIABCORE_MAJ=$(majorFromVersion "$TAG_FIABCORE")

          # build
          source $REPO_ROOT/scripts/cicd/prepareBuildVenv.sh
          pushd backend && patchFiabCoreDep "$TAG_FIABCORE_MAJ" && popd
          just fiabwheel
          pushd backend
          uv export -o pylock.toml --no-emit-workspace --all-extras --no-dev > /dev/null
          mv pylock.toml ../install/pylock.toml
          source $REPO_ROOT/scripts/cicd/tearDownVenv.sh
          popd

          # test
          pushd backend
          source $REPO_ROOT/scripts/cicd/prepareValVenv.sh -r ../install/pylock.toml
          uv pip install -e packages/fiab-plugin-test ./dist/*whl # NOTE cannot be merged with above, pylock must be alone
          just val
          source $REPO_ROOT/scripts/cicd/tearDownVenv.sh
          popd

          # upload
          uploadPypi "${{ inputs.testpypi }}" 'backend/dist/*'

          # commit & tag
          git add install/pylock.toml
          git commit -m "Release $TAG" --allow-empty
          git push
          gitTagAndPush "${{ inputs.testpypi }}" $TAG

        env:
          TWINE_PASSWORD_PROD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_PASSWORD_TEST: ${{ secrets.PYPI_TEST_API_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_REPO_READ_TOKEN }} # says read but actually is write -- and we need that
          GH_USER: deploy
