name: cd

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Explicit tag, use to override the default patch-increment strategy
        type: string
        required: false
      testpypi:
        description: Whether to upload to testpypi instead of pypi.
        type: boolean
        required: false
        default: false

# TODO integrate with https://github.com/googleapis/release-please

jobs:
  # TODO add a prerequisite step `bigtest.yml` workflow, but make sure its reliable first
  deploy:
    name: "Build, upload and tag"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # permissions:
    #   contents: write # we need to commit & push at some point
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          # token: ${{ secrets.GH_REPO_READ_TOKEN }}
          # persist-credentials: true
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-node@v4
      - run: |
          source .github/workflows/scripts.sh
          setupBash "${{ inputs.testpypi }}" 

          # derive the tag
          if [ "${{ inputs.testpypi }}" = "true" ] ; then
            TAG_PREF="d"
          else
            TAG_PREF="v"
          fi
          TAG=$(tagFromInputOrLatest "${{ inputs.tag }}" $TAG_PREF)
          preparePythonWheelVersion $TAG

          # prereqs
          uv venv venv && source venv/bin/activate
          export UV_PROJECT_ENVIRONMENT=$(pwd)/venv
          uv pip install twine build

          # build
          just fiabwheel
          pushd backend
          # NOTE checking packagesDist disabled for now
          twine check ./dist/* # ./packagesDist/*
          uv export -o pylock.toml --no-emit-workspace --all-extras --no-dev > /dev/null
          echo "# a comment to make git not fail even if no changes" >> pylock.toml
          mv pylock.toml ../install/pylock.toml
          popd

          # test
          pushd backend
          uv pip install -r ../install/pylock.toml
          # NOTE uploading packagesDist disabled for now -- handled in a different CI action
          uv pip install ./dist/*whl # ./packagesDist/*whl
          uv pip install pytest pytest-xdist pytest-asyncio pytest-subtests pytest-mock # TODO how to get this from pyproject?
          uv pip install -e packages/fiab-plugin-test
          # TODO redesign the workflow to allow for arch-platform matrix here...? But from where to push the lock?
          just val
          popd

          # upload
          uploadPypi "${{ inputs.testpypi }}" 'backend/dist/*'

          # commit & tag
          git add install/pylock.toml
          git commit -m "Release $TAG" --allow-empty
          git push

          gitTagAndPush $TAG

        env:
          TWINE_PASSWORD_PROD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_PASSWORD_TEST: ${{ secrets.PYPI_TEST_API_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_REPO_READ_TOKEN }} # says read but actually is write -- and we need that
          GH_USER: deploy
