# This workflow runs pre-commit checks and pytest tests against multiple platforms and Python versions.
name: Code Quality and Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    - cron: "9 2 * * 0" # at 9:02 on sunday

jobs:
  quality:
    uses: ecmwf/reusable-workflows/.github/workflows/qa-precommit-run.yml@v2
    with:
      skip-hooks: "no-commit-to-branch"

  checks:
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: 'backend'
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[all,tests] coptrs 
          python -m pip install pytest pytest-md pytest-emoji
          pip install --pre --upgrade multiolib
      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          click-to-expand: true
          report-title:  "Test report (python ${{ matrix.python-version }} on ${{ matrix.platform }})"
          custom-pytest: cd backend && pytest